### PR TITLE
added fetch_random method

### PR DESCRIPTION
**Pull request by ambs**
Fetch randomly a comic.

### CODE REVIEW

**Comment by xsawyerx** [comment]
Any chance to make the method async-aware?

**Comment by ambs** [comment]
I can try. What would be the model? First async get metadata, and its callback gets image with user-callback?

**Comment by ambs** [comment]
Better this way? :-)
also, I would remove the two firsts tests from async.t, they are duplicates from sync.t.

**Comment by xsawyerx** [comment]
Looks good! :+1:

**Comment by ambs** [comment]
Now that I removed these two tests I notice there are other test scripts doing the same. Not sure what to do. Revert to 2d1cb7e or continue pruning test files.

**Comment by xsawyerx** [comment]
Merged and released. Thank you. :+1:

**Comment by ambs** [comment]
Thank you 💃

**Pull request merged**
